### ISSUE TITLE
获取隐藏空间列表返回{"errno":-6,"request_id":279373562259991769}

### ISSUE THREAD

**Issue by miaomiaojianglove** [nvv5/BaiduSafeBox#2]
大佬这是什么原因呀

**Comment by nvv5** [comment]
是不是隐藏空间没有开启，或者密码不对，没有几种可能性

**Comment by miaomiaojianglove** [comment]
隐藏空间开启了 然后密码也正确我测试过
 我复制PC端的cookie 没有问题能拿到隐藏空间列表 
然而我通过 百度网盘扫码登陆的接口https://passport.baidu.com/v3/login/main/qrbdusslogin?v=1657790831875&bduss=xxx 返回的cookie 操作隐藏空间则不行; 求大佬指点如何获取完整的cookie 或者能模拟请求 获得cookie 感谢大佬
